# Generated by Django 3.1.3 on 2020-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0004_auto_20201204_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='last_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
