# Generated by Django 3.1.3 on 2020-12-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0005_auto_20201204_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(default=' ', max_length=30, null=True),
        ),
    ]
